### ISSUE TITLE
timestamp None warning

### ISSUE THREAD

**Issue by bk111** [Lyken17/tiny-whisper#1]
Traceback (most recent call last):
  File "/root/distil-long-srt.py", line 40, in <module>
    hf_pipeline_to_srt(result, output_file=output_srt)
  File "/root/utils.py", line 23, in hf_pipeline_to_srt
    start, end = map(convert_time, chk["timestamp"])
  File "/root/utils.py", line 9, in convert_time
    seconds, milliseconds = map(int, str(data).split("."))
ValueError: invalid literal for int() with base 10: 'None'

**Comment by Lyken17** [comment]
can you provide your mp3 for reproducement?

**Comment by bk111** [comment]
> can you provide your mp3 for reproducement?

please download the zip and unzip, 10m.mp3 with model_id = "distil-whisper/distil-medium.en"
https://forum.chinese-learning.me/viewtopic.php?f=5&t=456

**Comment by jarleigel** [comment]
Hi!
I also get the same error: 
ValueError: invalid literal for int() with base 10: 'None'

Looking at the data that is comming into the "convert_time" function, I can see that the last timstamp has "None" in the time field:
{"timestamp": (1258.64, 1259.44), "text": " God lunsj så lenge,"}, 
{"timestamp": (1259.66, 1262.3), "text": " og fortsatt god dag til dere som ikke blir med videre."}, 
{"timestamp": (1262.56, **None**), "text": " Takk for nå."}]

I suppose the error is that Python is not able to convert the string to int?

Thank you,
Jarle
